# Python implementations of orbital similarity criteria:
# - two variants of D-criterion by Southworth & Hawkins
# - D-criterion by Drummond
# - rho_2 distance by Kholshevnikov
# - DH-criterion by Jopek
#
# Please cite our article 'Relaxed triangle inequality for the orbital similarity criterion by 
# Southworth and Hawkins and its variants' (https://link.springer.com/article/10.1007/s10569-019-9884-6)
# if you use this code for your public work.
#
# Author: Yulia Milanova (yulia.milanova@gmail.com)
# Year:   2018
#
# input: the name of a test file generated by the celestial.orbits.net_algo.distance.DistTest program

import sys
import math
import orbital_similarity as criteria


Delta_SH = 0
Delta_SH2 = 0
Delta_D = 0
Delta_RHO2 = 0 
Delta_H = 0 
i = 1
with open(sys.argv[1], 'r') as file:
    for line in file:
        N1,Name1,q1,e1,i1,Omega1,omeg1,N2,Name2,q2,e2,i2,Omega2,omeg2,DD_SH,DD_SH2,DD_D,DD_RHO2,DD_H = line.split(',') 
        q1 = float(q1)
        e1 = float(e1)
        i1 = float(i1)
        Omega1 = float(Omega1)
        omeg1 = float(omeg1)
        q2 = float(q2)
        e2 = float(e2)
        i2 = float(i2)
        Omega2 = float(Omega2)
        omeg2 = float(omeg2)
        DD_SH = float(DD_SH)
        DD_SH2 = float(DD_SH2)
        DD_D = float(DD_D)
        DD_RHO2 = float(DD_RHO2)
        DD_H = float(DD_H)
        YD_SH  = criteria.DSH(q1, e1, i1, Omega1, omeg1, q2, e2, i2, Omega2, omeg2)
        YD_SH2 = criteria.DSH2(q1, e1, i1, Omega1, omeg1, q2, e2, i2, Omega2, omeg2)
        YD_D   = criteria.DD(q1, e1, i1, Omega1, omeg1, q2, e2, i2, Omega2, omeg2)
        YRHO_2 = criteria.RHO2(q1, e1, i1, Omega1, omeg1, q2, e2, i2, Omega2, omeg2)
        YD_H   = criteria.DH(q1, e1, i1, Omega1, omeg1, q2, e2, i2, Omega2, omeg2)
        if math.fabs(DD_SH-YD_SH) > Delta_SH:
            Delta_SH = math.fabs(DD_SH-YD_SH)
            params11 = [q1, e1, i1, Omega1, omeg1 ]
            params12 = [q2, e2, i2, Omega2, omeg2 ]
            i_max1 = i
        if math.fabs(DD_SH2-YD_SH2) > Delta_SH2:
            Delta_SH2 = math.fabs(DD_SH2-YD_SH2)
            params21 = [q1, e1, i1, Omega1, omeg1 ]
            params22 = [q2, e2, i2, Omega2, omeg2 ]
            i_max2 = i
        if math.fabs(DD_D-YD_D) > Delta_D:
            Delta_D = math.fabs(DD_D-YD_D)
            params31 = [q1, e1, i1, Omega1, omeg1 ]
            params32 = [q2, e2, i2, Omega2, omeg2 ]
            i_max3 = i
        if math.fabs(DD_RHO2-YRHO_2) > Delta_RHO2:
            Delta_RHO2 = math.fabs(DD_RHO2-YRHO_2)
            params41 = [q1, e1, i1, Omega1, omeg1 ]
            params42 = [q2, e2, i2, Omega2, omeg2 ]
            i_max4 = i
        if math.fabs(DD_H-YD_H) > Delta_H:
            Delta_H = math.fabs(DD_H-YD_H)
            params51 = [q1, e1, i1, Omega1, omeg1 ]
            params52 = [q2, e2, i2, Omega2, omeg2 ]
            i_max5 = i
                  
        i+=1
print('Distance calculation check result: Delta_* = max|D_*(file) - D_*(calc)|:\n',
      'Delta_SH =',Delta_SH,'\n','line number in file =',i_max1,'\n','orbit 1 elements:', params11,'\n',
      'orbit 2 elements:', params12,'\n',
      'Delta_SH2 =',Delta_SH2,'\n','line number in file =',i_max2,'\n','orbit 1 elements:', params21,'\n',
      'orbit 2 elements:', params22,'\n',
      'Delta_D =',Delta_D,'\n','line number in file =',i_max3,'\n','orbit 1 elements:', params31,'\n',
      'orbit 2 elements:', params32,'\n',
      'Delta_RHO2 =',Delta_RHO2,'\n','line number in file =',i_max4,'\n','orbit 1 elements:', params41,'\n',
      'orbit 2 elements:', params42,'\n',
      'Delta_H =',Delta_H,'\n','line number in file =',i_max5,'\n','orbit 1 elements:', params51,'\n',
      'orbit 2 elements:', params52)
